// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.3
// - protoc             v5.29.3
// source: server/scanner.proto

package server

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationScannerScan = "/api.server.Scanner/Scan"

type ScannerHTTPServer interface {
	Scan(context.Context, *ScanRequest) (*ScanReply, error)
}

func RegisterScannerHTTPServer(s *http.Server, srv ScannerHTTPServer) {
	r := s.Route("/")
	r.GET("/scan/{name}", _Scanner_Scan0_HTTP_Handler(srv))
}

func _Scanner_Scan0_HTTP_Handler(srv ScannerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ScanRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationScannerScan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Scan(ctx, req.(*ScanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ScanReply)
		return ctx.Result(200, reply)
	}
}

type ScannerHTTPClient interface {
	Scan(ctx context.Context, req *ScanRequest, opts ...http.CallOption) (rsp *ScanReply, err error)
}

type ScannerHTTPClientImpl struct {
	cc *http.Client
}

func NewScannerHTTPClient(client *http.Client) ScannerHTTPClient {
	return &ScannerHTTPClientImpl{client}
}

func (c *ScannerHTTPClientImpl) Scan(ctx context.Context, in *ScanRequest, opts ...http.CallOption) (*ScanReply, error) {
	var out ScanReply
	pattern := "/scan/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationScannerScan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
